name: Update versions file

env:
  NEW_VERSION: ""

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      newVersion:
        type: string
        required: true
        description: "The new 'latest' version"
        required: true
  
jobs:
  update-versions-file:
    name: Update version map
    runs-on: ubuntu-20.04
  
    
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Update versions file
      run: |
        sed -i 's/\t"latest": .*/\t"latest": "${{ inputs.newVersion }}"/g' versions.json

    - name: Commit and push changes
      run: |
        # configure user
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
    
        # stage any file changes to be committed
        git add .
    
        # make commit with staged changes
        git commit -m 'New version: ${{ inputs.newVersion }}'
    
        # push the commit back up to source GitHub repository
        git push
